<?php

namespace App\Enums;

enum TaxRegimeEnum: string
{
    case REGIMEN_GENERAL_DE_LEY_PERSONAS_MORALES = '601';
    case REGIMEN_SIMPLIFICADO_DE_LEY_PERSONAS_MORALES = '602';
    case PERSONAS_MORALES_CON_FINES_NO_LUCRATIVOS = '603';
    case REGIMEN_DE_PEQUENOS_CONTRIBUYENTES = '604';
    case REGIMEN_DE_SUELDOS_Y_SALARIOS = '605';
    case REGIMEN_DE_ARRENDAMIENTO = '606';
    case REGIMEN_DE_ENAJENACION_O_ADQUISICION_DE_BIENES = '607';
    case REGIMEN_DE_LOS_DEMAS_INGRESOS = '608';
    case REGIMEN_DE_CONSOLIDACION = '609';
    case RESIDENTES_EN_EL_EXTRANJERO_SIN_ESTABLECIMIENTO_PERMANENTE = '610';
    case INGRESOS_POR_DIVIDENDOS_SOCIOS_Y_ACCIONISTAS = '611';
    case PERSONAS_FISICAS_CON_ACTIVIDADES_EMPRESARIALES_Y_PROFESIONALES = '612';
    case REGIMEN_INTERMEDIO_PERSONAS_FISICAS_CON_ACTIVIDADES_EMPRESARIALES = '613';
    case INGRESOS_POR_INTERESES = '614';
    case INGRESOS_POR_OBTENCION_DE_PREMIOS = '615';
    case SIN_OBLIGACIONES_FISCALES = '616';
    case PEMEX = '617';
    case REGIMEN_SIMPLIFICADO_DE_LEY_PERSONAS_FISICAS = '618';
    case INGRESOS_POR_OBTENCION_DE_PRESTAMOS = '619';
    case SOCIEDADES_COOPERATIVAS_DE_PRODUCCION = '620';
    case REGIMEN_DE_INCORPORACION_FISCAL = '621';
    case ACTIVIDADES_AGRICOLAS_GANADERAS_SILVICOLAS_Y_PESQUERAS_PM = '622';
    case REGIMEN_OPCIONAL_PARA_GRUPOS_DE_SOCIEDADES = '623';
    case REGIMEN_DE_LOS_COORDINADOS = '624';
    case ACTIVIDADES_EMPRESARIALES_A_TRAVES_DE_PLATAFORMAS_TECNOLOGICAS = '625';
    case REGIMEN_SIMPLIFICADO_DE_CONFIANZA = '626';

    //Hacer label() y foSelect();
}